# Cocktails here are generally from specific bars, where I know the ingredient list,
# more or less, but not the ratios or specific brands.  I may experiment to find
# mkehrt-approved versions.
---
repeat-offender:
  name: Repeat Offender
  origin: Luna Park, San Francisco
  ingredients: whiskey (probably bourbon), smokey mezcal, chocolate bitters, orange
  
smoking-gun:
  name: Somking Gun
  origin: Hideout, SF
  ingredients: Ardbeg 10, Gran Classico, Cynar, coffee bitters
  
yellow-king:
  name: Yellow King
  origin: Blackbird, SF
  ingredients: Aveze (subst Suze or maybe Selars), dolin blanc, Gran Classico (?)
